-- ═══════════════════════════════════════════════════════════
--  此檔案已改用 Appwrite（非 SQL 資料庫）
--  請依下方說明在 Appwrite Console 手動建立 Collection
--
--  Console 位址：https://cloud.appwrite.io
-- ═══════════════════════════════════════════════════════════

-- ┌─────────────────────────────────────────────────────────┐
-- │  Collection 1：dashboard_config                         │
-- ├─────────────────────────────────────────────────────────┤
-- │  Attribute  │ Type    │ Size   │ Required │ Default     │
-- │  key        │ String  │ 100    │ ✓        │ -           │
-- │  value      │ String  │ 65535  │ ✓        │ -           │
-- ├─────────────────────────────────────────────────────────┤
-- │  Index：key (unique)                                    │
-- │  Permissions：any → create / read / update / delete    │
-- └─────────────────────────────────────────────────────────┘

-- ┌─────────────────────────────────────────────────────────┐
-- │  Collection 2：calendar_events                          │
-- ├─────────────────────────────────────────────────────────┤
-- │  Attribute  │ Type    │ Size   │ Required │             │
-- │  title      │ String  │ 500    │ ✓        │             │
-- │  date       │ String  │ 10     │ ✓        │ YYYY-MM-DD  │
-- │  time       │ String  │ 10     │          │             │
-- │  note       │ String  │ 2000   │          │             │
-- │  color      │ String  │ 20     │          │ #58a6ff     │
-- ├─────────────────────────────────────────────────────────┤
-- │  Permissions：any → create / read / update / delete    │
-- └─────────────────────────────────────────────────────────┘

-- ┌─────────────────────────────────────────────────────────┐
-- │  Collection 3：personal_history                         │
-- ├─────────────────────────────────────────────────────────┤
-- │  Attribute   │ Type     │ Required │                    │
-- │  title       │ String   │ ✓        │                    │
-- │  description │ String   │          │                    │
-- │  year        │ Integer  │ ✓        │                    │
-- │  month       │ Integer  │ ✓        │ 1-12              │
-- │  day         │ Integer  │ ✓        │ 1-31              │
-- ├─────────────────────────────────────────────────────────┤
-- │  Index：month + day (key)                               │
-- │  Permissions：any → create / read / update / delete    │
-- └─────────────────────────────────────────────────────────┘
